# Generated by Django 6.0.2 on 2026-02-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_seed_normative_coefficients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normativecoefficient',
            options={'ordering': ['normative_type'], 'verbose_name': 'Normativ koeffitsient', 'verbose_name_plural': 'Normativ koeffitsientlar'},
        ),
        migrations.AlterModelOptions(
            name='staffcomposition',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Xodim tarkibi', 'verbose_name_plural': 'Xodimlar tarkibi'},
        ),
        migrations.AlterField(
            model_name='normativecoefficient',
            name='additional_change_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Qo'shimcha o'zgartirish (bet)"),
        ),
        migrations.AlterField(
            model_name='normativecoefficient',
            name='complexity_level_1',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6, verbose_name='I toifa'),
        ),
        migrations.AlterField(
            model_name='normativecoefficient',
            name='complexity_level_2',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=6, verbose_name='II toifa'),
        ),
        migrations.AlterField(
            model_name='normativecoefficient',
            name='complexity_level_3',
            field=models.DecimalField(decimal_places=2, default=1.2, max_digits=6, verbose_name='III toifa'),
        ),
        migrations.AlterField(
            model_name='normativecoefficient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='normativecoefficient',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='normativecoefficient',
            name='new_document_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yangi (bet/oy)'),
        ),
        migrations.AlterField(
            model_name='normativecoefficient',
            name='normative_type',
            field=models.CharField(choices=[('technical_regulation', 'Technical regulation'), ('shnq', 'SHNQ'), ('eurocode', 'Eurocode'), ('standard_srn_qr_mqn', 'Standard/SRN/QR/MQN'), ('methodical_guide', 'Methodical guide')], max_length=64, unique=True, verbose_name='Normativ turi'),
        ),
        migrations.AlterField(
            model_name='normativecoefficient',
            name='rework_harmonization_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Qayta ishlash: uyg'unlashtirish (bet)"),
        ),
        migrations.AlterField(
            model_name='normativecoefficient',
            name='rework_modification_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qayta ishlash: muvofiqlashtirish (bet)'),
        ),
        migrations.AlterField(
            model_name='normativecoefficient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='staffcomposition',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Koeffitsient'),
        ),
        migrations.AlterField(
            model_name='staffcomposition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='staffcomposition',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='staffcomposition',
            name='mrot',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='MROT'),
        ),
        migrations.AlterField(
            model_name='staffcomposition',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='staffcomposition',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='staffcomposition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
    ]
