# Generated by Django 6.0.2 on 2026-02-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_documentcalculation_research_and_final_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcalculation',
            name='normative_type',
            field=models.CharField(choices=[('technical_regulation', 'Technical regulation'), ('shnq', 'SHNQ'), ('eurocode', 'Eurocode'), ('standard', 'Standard'), ('srn', 'SRN'), ('qr', 'QR'), ('mqn', 'MQN'), ('methodical_guide', 'Methodical guide')], max_length=64, verbose_name='Normativ turi'),
        ),
        migrations.AlterField(
            model_name='normativecoefficient',
            name='normative_type',
            field=models.CharField(choices=[('technical_regulation', 'Technical regulation'), ('shnq', 'SHNQ'), ('eurocode', 'Eurocode'), ('standard', 'Standard'), ('srn', 'SRN'), ('qr', 'QR'), ('mqn', 'MQN'), ('methodical_guide', 'Methodical guide')], max_length=64, unique=True, verbose_name='Normativ turi'),
        ),
    ]
