# Generated by Django 6.0.2 on 2026-02-27 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0008_alter_documentcalculation_normative_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCalculationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Kategoriya nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Hujjat hisobi kategoriyasi',
                'verbose_name_plural': 'Hujjat hisobi kategoriyalari',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='documentcalculation',
            name='completed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='01.01.2026 holatiga bajarilgan'),
        ),
        migrations.AddField(
            model_name='documentcalculation',
            name='development_deadline',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ishlab chiqish muddati'),
        ),
        migrations.AddField(
            model_name='documentcalculation',
            name='executor_organization',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ishni bajaruvchi tashkilot'),
        ),
        migrations.AddField(
            model_name='documentcalculation',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='documentcalculation',
            name='planned_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='2026-yilga rejalashtirilgan'),
        ),
        migrations.AddField(
            model_name='documentcalculation',
            name='calculation_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_calculations', to='app_main.documentcalculationcategory', verbose_name='Hisob-kitob kategoriyasi'),
        ),
    ]
